name: Bug Report
description: When a feature is not behaving as expected.
labels: [bug]
assignees: paradoxical-autumn
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add media to help explain your problem
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: reporters
    attributes:
      label: Reporters
      description: Add any usernames / discord handles of reporters here. This is used to credit you in release notes.
    validations:
      required: true
